### ISSUE TITLE
Problem with Beyond Australis

### ISSUE THREAD

**Issue by Weasy666** [johngraciliano/simplewhite#12]
![unbenannt](https://cloud.githubusercontent.com/assets/11967542/10950318/61dcce56-8337-11e5-9b87-97697a4570f2.png)
Like you can see on the picture, there is a transparent space between the border of the bar and the input panel.
I'm using Simple White X 2.2b18.x1.03 with Firefox 42 on Windows 10

**Comment by johngraciliano** [comment]
Thank you for the report.  I will investigate this.

**Comment by Weasy666** [comment]
The Problem is gone. Dunno why, but now everything is alright.
