### ISSUE TITLE
Improve support for Light Weight Themes

### ISSUE THREAD

**Issue by johngraciliano** [johngraciliano/simplewhite#16]
_Light weight themes_ can be used in conjunction with **_Simple White X**_ and other _complete (heavy weight) themes_ by using the **_Persona Switcher**_ extension.  However this theme will present some incompatibility, especially if combined with _dark_ light weight themes, e.g., **_Dark Fox**_.  In such case, the toolbar buttons change to fit a dark background, but main toolbar background remains unchanged making the buttons almost invisible.  In such case the toolbar background should become dark or the buttons should remain unchanged.  The real question is:  _Should **any** light weight theme become visible through the main toolbar?_

**_(Your feedback is requested!)**_

**Comment by Lootyhoof** [comment]
I might be a little biased here, all things considered, but personally I quite like having some slight transparency in the toolbars, so you can still see the image somewhat behind them (reminder that there are some instances where the whole window title area isn't skinned, such as when the titlebar is enabled, or on Linux, so even less of the persona is able to be seen). See below for what I mean, in both dark and light personas; note that these are used as-is in my current implementation in [White Moon](https://github.com/Lootyhoof/whitemoon) (as well as its sibling, [Dark Moon](https://github.com/Lootyhoof/darkmoon)).

Dark persona:

![Dark persona](https://i.imgur.com/tGOlyy6.png)

Light persona:

![Light persona](http://i.imgur.com/qUqUrhI.png)

**Comment by johngraciliano** [comment]
@Lootyhoof :+1:  Thank you for your advise.  I have been experimenting with similar settings, but I was not using a gradient (with a varying range) for the background of the navigation bar as I believe you are.  The color ranges you use are excellent, and I hope you do not mind if I use them. The same goes for the selected tab, of course.  I am not sure I want to leave such a low alpha (opacity) for the non-selected tabs for two reasons: one is that I worry some personas can make the text hard to read, and another is it may differ to much from how the theme looks without personas.  This is what I have:
![img1](https://cloud.githubusercontent.com/assets/13938911/12327079/68ab3914-baa2-11e5-9bee-94eddd98c6be.png)
![img2](https://cloud.githubusercontent.com/assets/13938911/12327085/6d942184-baa2-11e5-8b94-9941e3f41438.png)
I will see what I get after checking with your values.

**Comment by Lootyhoof** [comment]
Certainly, feel free to use what you like from my themes; we're both working on open-source projects, after all. It would be worthwhile to visit most of the `:-moz-lwtheme` styles in my [browser.css](https://github.com/Lootyhoof/whitemoon/blob/master/src/chrome/browser/browser.css), particularly for the tab styles (as there are a few; note that the styles related to `border` may not apply here as I recently converted the tabs to pure CSS rather than using a `border-image`), however, for reference, the nav-bar styles are:
Dark persona: `linear-gradient(rgba(5,5,5,0.9), rgba(5,5,5,0.6))`
Light persona: `linear-gradient(rgba(250,250,250,0.9), rgba(250,250,250,0.5))`

As for the non-selected tabs, to be honest I do agree. I'll most likely change those soon.

**Comment by johngraciliano** [comment]
Thank you for the details.  I am checking your [browser.css](https://github.com/Lootyhoof/whitemoon/blob/master/src/chrome/browser/browser.css) right now.  I am just happy it is so much cleaner than the _Frankenstein's creature_ I have with the name [browser-common.css](https://github.com/johngraciliano/simplewhite/blob/master/whitefox/browser/browser-common.css). (It is indeed pieced together from many corpses!  And I know you know that, but I prefer to leave it that way so I can better match it with the _browser.css_ in the **_default**_ theme for **Firefox**.) 

p.s. Please note the images in my previous comment will not be produced by the theme in the project area.  They are produced by my modified local copy.

p.p.s.  I included the persona [Plaited Monochrome](https://addons.mozilla.org/en-US/firefox/addon/monochrome-knots/) because I think is one of the most visually challenging. Indeed the light border I use for the tabs may be to faint to be seen there, so that may change.

p.p.p.s. (_out of topic_) Wow, the interface here (at Github) keeps changing...

**Comment by johngraciliano** [comment]
This issue was left open as a reminder, but it does not seem relevant anymore.  The only thing regarding this is a desire for more contrast for the title bar buttons min/max/close under **Windows 10**.  I may agree to the change if there were more voices asking for it but no one else had come forward.  Thus I leave the issue as closed.
