### ISSUE TITLE
Invisible background on fullscreen video warning

### ISSUE THREAD

**Issue by ghost** [johngraciliano/simplewhite#20]
Firefox's new(ish) notice about having turned on fullscreen when playing a video is invisible and looks rather bad, see the screenshots below (Simple White first, default theme second).

![Simple White X](https://cloud.githubusercontent.com/assets/6289234/12498408/a1a0ff3c-c0a2-11e5-8df9-7cc4993d4f1b.png)

![Default](https://cloud.githubusercontent.com/assets/6289234/12498458/fd25c7b6-c0a2-11e5-9c25-69318542d9f5.png)

**Comment by johngraciliano** [comment]
Thank you for that information, I have not paid attention to that, I am not sure I want a background.  However, if there is text it should be readable, so it may need a background.  If there is a red frame I certainly do not want that.

**Comment by ghost** [comment]
The red frame is something I added to highlight the barely visible text. This is how it looks on a light background:

![fullscreen](https://cloud.githubusercontent.com/assets/6289234/12530482/d194a16e-c1e0-11e5-82f5-c89d94cbd8fb.png)

**Comment by johngraciliano** [comment]
I have seen that and I am not sure I would change it.  I would rather show nothing at all, yet a theme should not do that.  If I change anything, it may be adding some shadow or light outline to help the text be more visible.  But I still need to look at it more carefully.

**Comment by Lootyhoof** [comment]
It would be advisable to add some sort of semi-transparent `background-color`. Perhaps `rgba(255,255,255,.3)`?

**Comment by johngraciliano** [comment]
Sorry to all, I have been busy with #16 and #19.  I have noticed this notification is a bit changed from what it was.  It shall be re-designed  for a future release, not the next one.

**Comment by johngraciliano** [comment]
All things considered a semi-transparent background will be part of the solution, as seen in the sample:
![fullscreen](https://cloud.githubusercontent.com/assets/13938911/12806894/210710d8-cad8-11e5-9edb-38622b61c7ab.png)
The change is not merged yet.

**Comment by johngraciliano** [comment]
After a small redesign the sample shown before, the solution is out in the release [v2.2b18.x1.11](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x1.11).
