### ISSUE TITLE
Incorrect displaying of the video window

### ISSUE THREAD

**Issue by 100fanti** [johngraciliano/simplewhite#38]
Open any video or mp3 file from your computer via Firefox (browser versions 53, 54) to see the problem.
The default skin all correctly.
![5](https://cloud.githubusercontent.com/assets/25398151/22730016/535b007a-edf6-11e6-9ca9-1ec428752517.jpg)
![6](https://cloud.githubusercontent.com/assets/25398151/22730018/55abcda0-edf6-11e6-9b2c-6035f972e077.jpg)

**Comment by johngraciliano** [comment]
@100fanti:
Yes I can see the problem clearly and it is certainly bad.  I will see what I can do.

**Comment by johngraciliano** [comment]
@100fanti:
Please try the xpi files in [this release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.01%2BT2).
And again, thank you for bringing my attention to this issue.  There were a few things more I had to fix that affect **Firefox 52** (and possibly earlier). In particular, support for the *close captions* button.

**Comment by 100fanti** [comment]
I can check only Firefox 53 and 54 versions, all right now.
2.2b18.x2.01 + 03 / T3 looks better for your theme.
