### ISSUE TITLE
Broken downloads window.

### ISSUE THREAD

**Issue by 100fanti** [johngraciliano/simplewhite#39]
Only in Firefox 54.0a1 Nightly.

![1](https://cloud.githubusercontent.com/assets/25398151/23091563/12aa11ca-f5ca-11e6-8d77-34f6cefd8197.jpg)
![2](https://cloud.githubusercontent.com/assets/25398151/23091564/1bd19688-f5ca-11e6-9aa5-e03f166a0866.jpg)

**Comment by johngraciliano** [comment]
Thank you for the report.  Please try [this release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.01%2BT4).

**Comment by 100fanti** [comment]
OK. Thank you.

**Comment by 100fanti** [comment]
You can see the scroll bar, if the file has been moved or is missing.

![1](https://cloud.githubusercontent.com/assets/25398151/23339971/4378cca4-fc3e-11e6-85b0-c971a3a54096.jpg)

**Comment by johngraciliano** [comment]
@100fanti:  Try [this](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.01%2BT5).  Please, let me know if there is a problem remaining.   Thank you for your continuing assistance.

**Comment by 100fanti** [comment]
54.0a1 (2017-03-03) Animation from the download button has disappeared.

**Comment by johngraciliano** [comment]
@100fanti:  Thank you for keeping me informed.

Fortunately, **Mozilla** left the code for the presentation with the class _withProgressBar_.  I copied and modified a bit of their code to have **Firefox** acts as if that class is present.  The result seems to work fine.  I may want to test with earlier versions to make sure nothing is broken.  I added the [xpi](https://github.com/johngraciliano/simplewhite/releases/download/v2.2b18.x2.01%2BT5/SimpleWhiteX.T6.xpi) to the [last pre-release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.01%2BT5) I published.  Try it!

I can only hope **Mozilla** does not get rid of the code for the presentation _withProgressBar_.

**Comment by 100fanti** [comment]
55.0a1
Empty icon in the process of downloading

![1](https://cloud.githubusercontent.com/assets/25398151/26012330/e0ba1d34-375c-11e7-880d-aec4f22525bc.jpg)

**Comment by suishouen** [comment]
This is because Mozilla has removed codes for download progressbar and remaining time display on download toolbar icon.
See Bug 1329109 (https://bugzilla.mozilla.org/show_bug.cgi?id=1329109).

**Comment by johngraciliano** [comment]
This is now fixed (again) in the [latest release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.03).
