### ISSUE TITLE
Checked mark cannot shown on SSL error page

### ISSUE THREAD

**Issue by lychichem** [johngraciliano/simplewhite#4]
![default](https://cloud.githubusercontent.com/assets/9316590/10260959/2d686324-69b5-11e5-9392-e28f8b928096.PNG)
Under default theme it's OK. But under simple white X the checked mark circled is not shown.

**Comment by lychichem** [comment]
ZJU pages are our school's inner page and cannot access through Internet. Maybe you need to find another test link.

**Comment by johngraciliano** [comment]
I have not been able to reproduce this yet.  It definitively needs solving, please bring a better solution or convince me there is no other. I will keep trying to figure it out on my own too.
(I understand that using `!important` may prevent a similar problem elsewhere that has yet to be found.)
