### ISSUE TITLE
Webm GUI is messed up

### ISSUE THREAD

**Issue by DeadFuze** [johngraciliano/simplewhite#42]
http://i.imgur.com/Vg5Y1l7.png
Don't really have much to say about this

**Comment by DeadFuze** [comment]
Should probably note this is firefox 53.0b1

**Comment by johngraciliano** [comment]
This is issue #38.  I have a solution but it is in no official release yet.  Sorry I have been trying to catch up with other changes in Nightly and I have neglected making a formal release with the latest corrections.  Please try the last [pre-release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.01%2BT5) by installing [this .xpi](https://github.com/johngraciliano/simplewhite/releases/download/v2.2b18.x2.01%2BT5/SimpleWhiteX.T6.xpi).
If you wait a day or two I will merge my changes in this area and submit a new version to [AMO](https://addons.mozilla.org/en-US/firefox/).  
P.S. I will close this, but feel free to reopen it if you find a problem in the pre-release.
