### ISSUE TITLE
Moving a page refresh button

### ISSUE THREAD

**Issue by 100fanti** [johngraciliano/simplewhite#45]
Page refresh button has been moved to another location in 55.0a1 (2017-05-14) 

![2017-05-16_082435](https://cloud.githubusercontent.com/assets/25398151/26091153/14d41766-3a12-11e7-9501-600fc313aa45.jpg)

+update for https://github.com/johngraciliano/simplewhite/issues/39

**Comment by suishouen** [comment]
This is because Bug 1364090: Detach the reload and stop buttons from the location bar
(https://bugzilla.mozilla.org/show_bug.cgi?id=1364090) has landed.

Until johngraciliano will fix the problem, try adding the following to userChrome.css.


```
#reload-button {
  list-style-image: url("chrome://browser/skin/Toolbar.png");
  -moz-image-region: rect(0px, 90px, 18px, 72px);
}

#stop-button{
  list-style-image: url("chrome://browser/skin/Toolbar.png");
  -moz-image-region: rect(0px, 108px, 18px, 90px);
}

#reload-button:not([displaystop]) + #stop-button, #reload-button[displaystop] {
  visibility: collapse;
}
```

**Comment by 100fanti** [comment]
New changes in 55.0a1

![1](https://cloud.githubusercontent.com/assets/25398151/26501267/c6091be4-4241-11e7-8263-78eb0bcdc672.jpg)

![3](https://cloud.githubusercontent.com/assets/25398151/26501345/07313a02-4242-11e7-85a5-df9ca81f84de.jpg)

**Comment by suishouen** [comment]
/* 1st Issue */
    Try the follwing:
```
.toolbarbutton-menu-dropmarker {
  visibility: collapse;
}
```

/* 2nd issue */
    To solve this issue, you have to fix up "/whitefox/browser/customizableui/panelUI.css".
