### ISSUE TITLE
Active tab is not visible

### ISSUE THREAD

**Issue by 100fanti** [johngraciliano/simplewhite#46]
Firefox Nightly 55.0a1 (2017-05-20) 
Active tab is not visible.

![1](https://cloud.githubusercontent.com/assets/25398151/26276809/7e4ebb88-3d87-11e7-953e-2a0f64c12f94.jpg)

**Comment by suishouen** [comment]
Try the follwing:
```
.tabbrowser-tab[selected] {
  background: rgba(251,251,251,1) !important;
}
```
