### ISSUE TITLE
Icons in the address bar are big! [Wappalyzer plugin]

### ISSUE THREAD

**Issue by maicol07** [johngraciliano/simplewhite#48]
Hi,
Using the latest stable version of the theme (2.0.2) I found that Wappalyzer images are bigger than normal. See screenshots below.
Why?
Thanks
![immagine](https://user-images.githubusercontent.com/9463142/27253579-9d772eb8-5377-11e7-9fe4-64355618f71e.png)
![immagine](https://user-images.githubusercontent.com/9463142/27253580-abd02fb4-5377-11e7-86bf-357e9c21120a.png)

**Comment by johngraciliano** [comment]
Thank you for submitting this bug.
I am sorry, I am missing a bit of code that is on the default theme.  I am copying it to be included in the upcoming release. (Sorry, this is missing in the Trial I just published [here](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.03-trial).)

**Comment by johngraciliano** [comment]
This is now fixed in the [latest release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.03).

**Comment by maicol07** [comment]
Thanks
