### ISSUE TITLE
Drop-down icon visible in Back/Forward buttons (FF55)

### ISSUE THREAD

**Issue by wavexx** [johngraciliano/simplewhite#49]
I'm trying FF 55 (linux/debian here) for testing purposes, and I noticed that it introduces some quirks in the theme. The back/forward buttons in the toolbar now appear with the little down-down triangle within:

![2017-07-08t150512](https://user-images.githubusercontent.com/1017726/27985647-23bee98e-63ef-11e7-9cbe-99a04bb9130d.png)

Aside from that, I didn't notice any other issue.

**Comment by suishouen** [comment]
See https://github.com/johngraciliano/simplewhite/issues/45#issuecomment-304408247

**Comment by wavexx** [comment]
On Sat, Jul 08 2017, suishouen wrote:
> See #45 (comment)

Doesn't seem right, this will hide also extension's drop makers.
I'd go for something more conservative as:

  #back-button .toolbarbutton-menu-dropmarker,
  #forward-button .toolbarbutton-menu-dropmarker
  { display: none }

**Comment by suishouen** [comment]
You may be right.
I use no extensions having drop makers, so I don't think of them.

**Comment by johngraciliano** [comment]
I tried fixing this [here](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.03-trial).

**Comment by johngraciliano** [comment]
This is now fixed in the [latest release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x2.03).

**Comment by wavexx** [comment]
On Mon, Jul 31 2017, johngraciliano wrote:
> This is now fixed in the latest release.

Works perfectly.
Thanks!
