### ISSUE TITLE
Test this userstyle for the effect of hidding unsigned extensions warning

### ISSUE THREAD

**Issue by lychichem** [johngraciliano/simplewhite#6]
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

@-moz-document url("about:addons") {
  .addon.addon-view[type="extension"][notification="warning"][active="true"]{background-image: none}
  .addon.addon-view[type="extension"][notification="warning"][active="true"] > .warning{display: none}
}
I want you to give review of whether it mistakenly hides plugins warning or deprecated add-on warning. And if there's nothing wrong, just publish it to userstyles.org.

**Comment by lychichem** [comment]
It only works on addon management page, if you click "more", you can still see the warning about extensions as before.

**Comment by johngraciliano** [comment]
The omission of `!important` makes no differences, but having the relation character `>` makes the difference of the warning statements showing in the extension details frame/panel (linked with _more_).  You do not need to state the namespace.  The css hides all warnings from the _Extensions_ list in _about:addons_.  If you publish in userstyles.org I will include the link somewhere after the theme description.

It may be best if you only remove the warning statements from the list, but leave the background to warn the user.  I would simply make the line regarding the background a comment:
`@-moz-document url("about:addons"){`
`/*.addon-view[type="extension"][notification="warning"]{background-image: none;}*/`
`.addon-view[type="extension"]>.warning{display: none;}`
`}`

Now that you have me look at it carefully, I may want to change the icon used in the warning sign and review the background and/or text color.  Yet, I will not make changes at this time.
